

name: Node.js CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:  
      working-directory: ./Users/node prog  

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
     - uses: actions/checkout@master 
     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
     - run: sudo npm install -g jasmine
     - run: npm test
     - name: UI Testing succesfull
       run: echo running UI testinng
  
     - uses: actions/setup-java@v1
       with:
          java-version: '8.0.72' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
     - run: java -cp java UiTesting
       env:
        CI: true
