

name: Node.js CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:  
      working-directory: ./Users/node prog  

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
     - uses: actions/checkout@master 
     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
     - run: sudo npm install -g jasmine
     - run: npm test
     - name: UI Testing succesfull
       run: echo running UI testinng
  

       env:
        CI: true
